make the monitor brightness notification make sense

diff --git a/packages/desktop/hyprland/modules/hyprlandextra/hyprextra/scripts/backlight b/packages/desktop/hyprland/modules/hyprlandextra/hyprextra/scripts/backlight
--- a/packages/desktop/hyprland/modules/hyprlandextra/hyprextra/scripts/backlight
+++ b/packages/desktop/hyprland/modules/hyprlandextra/hyprextra/scripts/backlight
@@ -1,32 +1,46 @@
 #!/usr/bin/env bash
 
 iDIR="$HOME/.config/hyprextra/icons"
+SCALE="$1"
+
+# if scale is unset, return an error
+if [[ -z "$SCALE" ]]; then
+	echo "Error: scale is not set"
+	exit 1
+fi
 
 # Get brightness
 get_backlight() {
 	LIGHT=$(printf "%.0f\n" "$(brightnessctl g)")
+
+	# we may need to scale the value on some systems
+	# if the value is < 255 then we need to scale it
+	# 255 should become 100000
+	if [[ "$LIGHT" != 0 ]]; then
+		LIGHT=$((LIGHT * 100 / SCALE))
+	fi
 	echo "${LIGHT}"
 }
 
 # Get icons
 get_icon() {
 	current="$(get_backlight)"
-	if [[ ("$current" -ge "0") && ("$current" -le "19200") ]]; then
+	if [[ ("$current" -ge "0") && ("$current" -le "19") ]]; then
 		icon="$iDIR/brightness-20.png"
-	elif [[ ("$current" -ge "19200") && ("$current" -le "38400") ]]; then
+	elif [[ ("$current" -ge "19") && ("$current" -le "39") ]]; then
 		icon="$iDIR/brightness-40.png"
-	elif [[ ("$current" -ge "38400") && ("$current" -le "57600") ]]; then
+	elif [[ ("$current" -ge "39") && ("$current" -le "59") ]]; then
 		icon="$iDIR/brightness-60.png"
-	elif [[ ("$current" -ge "57600") && ("$current" -le "76800") ]]; then
+	elif [[ ("$current" -ge "59") && ("$current" -le "79") ]]; then
 		icon="$iDIR/brightness-80.png"
-	elif [[ ("$current" -ge "76800") && ("$current" -le "96000") ]]; then
+	elif [[ ("$current" -ge "79") ]]; then
 		icon="$iDIR/brightness-100.png"
 	fi
 }
 
 # Notify
 notify_user() {
-	notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$icon" "Brightness : $(get_backlight)"
+	notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$icon" "Brightness : $(get_backlight)%"
 }
 
 # Increase brightness
@@ -40,11 +54,11 @@ dec_backlight() {
 }
 
 # Execute accordingly
-if [[ "$1" == "--get" ]]; then
+if [[ "$2" == "--get" ]]; then
 	get_backlight
-elif [[ "$1" == "--inc" ]]; then
+elif [[ "$2" == "--inc" ]]; then
 	inc_backlight
-elif [[ "$1" == "--dec" ]]; then
+elif [[ "$2" == "--dec" ]]; then
 	dec_backlight
 else
 	get_backlight
